(define (problem p2056822651-overcooked)
  (:domain overcooked)

  (:objects
        pos-0-0 pos-0-1 pos-0-2 pos-0-3 pos-0-4 pos-0-5 pos-0-6 pos-1-0 pos-1-1 pos-1-2 pos-1-3 pos-1-4 pos-1-5 pos-1-6 pos-2-0 pos-2-1 pos-2-2 pos-2-3 pos-2-4 pos-2-5 pos-2-6 pos-3-0 pos-3-1 pos-3-2 pos-3-3 pos-3-4 pos-3-5 pos-3-6 pos-4-0 pos-4-1 pos-4-2 pos-4-3 pos-4-4 pos-4-5 pos-4-6 pos-5-0 pos-5-1 pos-5-2 pos-5-3 pos-5-4 pos-5-5 pos-5-6 pos-6-0 pos-6-1 pos-6-2 pos-6-3 pos-6-4 pos-6-5 pos-6-6 - location
        cutboard-01 - cutboard
        blender-01 - blender
        deliversquare-01 deliversquare-02 - deliversquare
        counter-01 counter-02 counter-03 counter-04 counter-05 counter-06 counter-07 counter-08 counter-09 counter-10 counter-11 counter-12 counter-13 counter-14 counter-15 counter-16 counter-17 counter-18 counter-19 counter-20 counter-21 counter-22 counter-23 counter-24 counter-25 counter-26 counter-27 counter-28 counter-29 counter-30 counter-31 counter-32 counter-33 counter-34 - counter
        plate-01 plate-02 plate-03 - plate
        carrot-01 carrot-02 - carrot
        banana-01 banana-02 - banana
        tomato-01 - tomato
  )

  (:init
        ;; How many quantities when chopping
        (quantity-after-chop onion-type num1)
        (quantity-after-chop tomato-type num1)
        (quantity-after-chop lettuce-type num1)
        (quantity-after-chop cucumber-type num1)
        (quantity-after-chop apple-type num1)
        (quantity-after-chop watermelon-type num1)
        (quantity-after-chop bread-type num2)
        (quantity-after-chop carrot-type num1)
        (quantity-after-chop banana-type num1)
        ;; numeric successor relation for numbers
        (succ num0 num1)
        (succ num1 num2)
        (succ num2 num3)
        (succ num3 num4)
        ;; type information for items
        (has-type carrot-01 carrot-type)
        (has-type carrot-02 carrot-type)
        (has-type banana-01 banana-type)
        (has-type banana-02 banana-type)
        (has-type tomato-01 tomato-type)
        ;; init cutboard and blender states -- empty at the start
        (chopped-food-count cutboard-01 num0)
        (smashed-food-count blender-01 num0)
        (plate-ingredient-count plate-01 num0)
        (plate-ingredient-count plate-02 num0)
        (plate-ingredient-count plate-03 num0)
        ;; location facts
        (clear pos-1-2)
        (clear pos-3-4)
        (clear pos-2-1)
        (clear pos-1-5)
        (clear pos-3-1)
        (clear pos-4-1)
        (clear pos-1-1)
        (clear pos-4-2)
        (clear pos-1-4)
        (clear pos-2-3)
        (clear pos-3-3)
        (clear pos-3-2)
        (clear pos-2-5)
        (clear pos-1-3)
        (on counter-01 pos-4-0)
        (on counter-02 pos-4-3)
        (on counter-03 pos-5-4)
        (on counter-04 pos-4-6)
        (on counter-05 pos-5-1)
        (on counter-06 pos-0-2)
        (on counter-07 pos-0-5)
        (on counter-08 pos-2-2)
        (on counter-09 pos-1-0)
        (on counter-10 pos-1-6)
        (on counter-11 pos-6-2)
        (on counter-12 pos-6-5)
        (on counter-13 pos-3-0)
        (on counter-14 pos-4-5)
        (on counter-15 pos-5-0)
        (on counter-16 pos-5-6)
        (on counter-17 pos-3-6)
        (on counter-18 pos-5-3)
        (on counter-19 pos-0-1)
        (on counter-20 pos-0-4)
        (on counter-21 pos-6-1)
        (on counter-22 pos-6-4)
        (on counter-23 pos-3-5)
        (on counter-24 pos-5-2)
        (on counter-25 pos-4-4)
        (on counter-26 pos-5-5)
        (on counter-27 pos-0-0)
        (on counter-28 pos-0-3)
        (on counter-29 pos-2-0)
        (on counter-30 pos-0-6)
        (on counter-31 pos-2-6)
        (on counter-32 pos-6-0)
        (on counter-33 pos-6-6)
        (on counter-34 pos-6-3)
        (on cutboard-01 pos-0-4)
        (on blender-01 pos-1-0)
        (on deliversquare-01 pos-0-5)
        (on deliversquare-02 pos-0-1)
        (is-switch pos-4-1)
        (switch-on pos-4-1)
        (is-block pos-4-2)
        (block-on pos-4-2)
        (is-block pos-1-2)
        (block-on pos-1-2)
        (at plate-01 pos-2-0)
        (at plate-02 pos-4-4)
        (at plate-03 pos-2-6)
        (at carrot-01 pos-0-3)
        (at carrot-02 pos-0-2)
        (at banana-01 pos-5-1)
        (at banana-02 pos-3-5)
        (at tomato-01 pos-1-6)
        (at agent-01 pos-2-4)
        (handempty agent-01)
        ;; directional adjacency facts
        (move-dir pos-2-4 pos-1-4 dir-left)
        (move-dir pos-2-4 pos-3-4 dir-right)
        (move-dir pos-2-4 pos-2-3 dir-up)
        (move-dir pos-2-4 pos-2-5 dir-down)
        (move-dir pos-1-2 pos-0-2 dir-left)
        (move-dir pos-1-2 pos-2-2 dir-right)
        (move-dir pos-1-2 pos-1-1 dir-up)
        (move-dir pos-1-2 pos-1-3 dir-down)
        (move-dir pos-3-4 pos-2-4 dir-left)
        (move-dir pos-3-4 pos-4-4 dir-right)
        (move-dir pos-3-4 pos-3-3 dir-up)
        (move-dir pos-3-4 pos-3-5 dir-down)
        (move-dir pos-2-1 pos-1-1 dir-left)
        (move-dir pos-2-1 pos-3-1 dir-right)
        (move-dir pos-2-1 pos-2-0 dir-up)
        (move-dir pos-2-1 pos-2-2 dir-down)
        (move-dir pos-1-5 pos-0-5 dir-left)
        (move-dir pos-1-5 pos-2-5 dir-right)
        (move-dir pos-1-5 pos-1-4 dir-up)
        (move-dir pos-1-5 pos-1-6 dir-down)
        (move-dir pos-3-1 pos-2-1 dir-left)
        (move-dir pos-3-1 pos-4-1 dir-right)
        (move-dir pos-3-1 pos-3-0 dir-up)
        (move-dir pos-3-1 pos-3-2 dir-down)
        (move-dir pos-4-1 pos-3-1 dir-left)
        (move-dir pos-4-1 pos-5-1 dir-right)
        (move-dir pos-4-1 pos-4-0 dir-up)
        (move-dir pos-4-1 pos-4-2 dir-down)
        (move-dir pos-1-1 pos-0-1 dir-left)
        (move-dir pos-1-1 pos-2-1 dir-right)
        (move-dir pos-1-1 pos-1-0 dir-up)
        (move-dir pos-1-1 pos-1-2 dir-down)
        (move-dir pos-4-2 pos-3-2 dir-left)
        (move-dir pos-4-2 pos-5-2 dir-right)
        (move-dir pos-4-2 pos-4-1 dir-up)
        (move-dir pos-4-2 pos-4-3 dir-down)
        (move-dir pos-1-4 pos-0-4 dir-left)
        (move-dir pos-1-4 pos-2-4 dir-right)
        (move-dir pos-1-4 pos-1-3 dir-up)
        (move-dir pos-1-4 pos-1-5 dir-down)
        (move-dir pos-2-3 pos-1-3 dir-left)
        (move-dir pos-2-3 pos-3-3 dir-right)
        (move-dir pos-2-3 pos-2-2 dir-up)
        (move-dir pos-2-3 pos-2-4 dir-down)
        (move-dir pos-3-3 pos-2-3 dir-left)
        (move-dir pos-3-3 pos-4-3 dir-right)
        (move-dir pos-3-3 pos-3-2 dir-up)
        (move-dir pos-3-3 pos-3-4 dir-down)
        (move-dir pos-3-2 pos-2-2 dir-left)
        (move-dir pos-3-2 pos-4-2 dir-right)
        (move-dir pos-3-2 pos-3-1 dir-up)
        (move-dir pos-3-2 pos-3-3 dir-down)
        (move-dir pos-2-5 pos-1-5 dir-left)
        (move-dir pos-2-5 pos-3-5 dir-right)
        (move-dir pos-2-5 pos-2-4 dir-up)
        (move-dir pos-2-5 pos-2-6 dir-down)
        (move-dir pos-1-3 pos-0-3 dir-left)
        (move-dir pos-1-3 pos-2-3 dir-right)
        (move-dir pos-1-3 pos-1-2 dir-up)
        (move-dir pos-1-3 pos-1-4 dir-down)
        (move-dir pos-4-0 pos-3-0 dir-left)
        (move-dir pos-4-0 pos-5-0 dir-right)
        (move-dir pos-4-0 pos-4-1 dir-down)
        (move-dir pos-4-3 pos-3-3 dir-left)
        (move-dir pos-4-3 pos-5-3 dir-right)
        (move-dir pos-4-3 pos-4-2 dir-up)
        (move-dir pos-4-3 pos-4-4 dir-down)
        (move-dir pos-5-4 pos-4-4 dir-left)
        (move-dir pos-5-4 pos-6-4 dir-right)
        (move-dir pos-5-4 pos-5-3 dir-up)
        (move-dir pos-5-4 pos-5-5 dir-down)
        (move-dir pos-4-6 pos-3-6 dir-left)
        (move-dir pos-4-6 pos-5-6 dir-right)
        (move-dir pos-4-6 pos-4-5 dir-up)
        (move-dir pos-5-1 pos-4-1 dir-left)
        (move-dir pos-5-1 pos-6-1 dir-right)
        (move-dir pos-5-1 pos-5-0 dir-up)
        (move-dir pos-5-1 pos-5-2 dir-down)
        (move-dir pos-0-2 pos-1-2 dir-right)
        (move-dir pos-0-2 pos-0-1 dir-up)
        (move-dir pos-0-2 pos-0-3 dir-down)
        (move-dir pos-0-5 pos-1-5 dir-right)
        (move-dir pos-0-5 pos-0-4 dir-up)
        (move-dir pos-0-5 pos-0-6 dir-down)
        (move-dir pos-2-2 pos-1-2 dir-left)
        (move-dir pos-2-2 pos-3-2 dir-right)
        (move-dir pos-2-2 pos-2-1 dir-up)
        (move-dir pos-2-2 pos-2-3 dir-down)
        (move-dir pos-1-0 pos-0-0 dir-left)
        (move-dir pos-1-0 pos-2-0 dir-right)
        (move-dir pos-1-0 pos-1-1 dir-down)
        (move-dir pos-1-6 pos-0-6 dir-left)
        (move-dir pos-1-6 pos-2-6 dir-right)
        (move-dir pos-1-6 pos-1-5 dir-up)
        (move-dir pos-6-2 pos-5-2 dir-left)
        (move-dir pos-6-2 pos-6-1 dir-up)
        (move-dir pos-6-2 pos-6-3 dir-down)
        (move-dir pos-6-5 pos-5-5 dir-left)
        (move-dir pos-6-5 pos-6-4 dir-up)
        (move-dir pos-6-5 pos-6-6 dir-down)
        (move-dir pos-3-0 pos-2-0 dir-left)
        (move-dir pos-3-0 pos-4-0 dir-right)
        (move-dir pos-3-0 pos-3-1 dir-down)
        (move-dir pos-4-5 pos-3-5 dir-left)
        (move-dir pos-4-5 pos-5-5 dir-right)
        (move-dir pos-4-5 pos-4-4 dir-up)
        (move-dir pos-4-5 pos-4-6 dir-down)
        (move-dir pos-5-0 pos-4-0 dir-left)
        (move-dir pos-5-0 pos-6-0 dir-right)
        (move-dir pos-5-0 pos-5-1 dir-down)
        (move-dir pos-5-6 pos-4-6 dir-left)
        (move-dir pos-5-6 pos-6-6 dir-right)
        (move-dir pos-5-6 pos-5-5 dir-up)
        (move-dir pos-3-6 pos-2-6 dir-left)
        (move-dir pos-3-6 pos-4-6 dir-right)
        (move-dir pos-3-6 pos-3-5 dir-up)
        (move-dir pos-5-3 pos-4-3 dir-left)
        (move-dir pos-5-3 pos-6-3 dir-right)
        (move-dir pos-5-3 pos-5-2 dir-up)
        (move-dir pos-5-3 pos-5-4 dir-down)
        (move-dir pos-0-1 pos-1-1 dir-right)
        (move-dir pos-0-1 pos-0-0 dir-up)
        (move-dir pos-0-1 pos-0-2 dir-down)
        (move-dir pos-0-4 pos-1-4 dir-right)
        (move-dir pos-0-4 pos-0-3 dir-up)
        (move-dir pos-0-4 pos-0-5 dir-down)
        (move-dir pos-6-1 pos-5-1 dir-left)
        (move-dir pos-6-1 pos-6-0 dir-up)
        (move-dir pos-6-1 pos-6-2 dir-down)
        (move-dir pos-6-4 pos-5-4 dir-left)
        (move-dir pos-6-4 pos-6-3 dir-up)
        (move-dir pos-6-4 pos-6-5 dir-down)
        (move-dir pos-3-5 pos-2-5 dir-left)
        (move-dir pos-3-5 pos-4-5 dir-right)
        (move-dir pos-3-5 pos-3-4 dir-up)
        (move-dir pos-3-5 pos-3-6 dir-down)
        (move-dir pos-5-2 pos-4-2 dir-left)
        (move-dir pos-5-2 pos-6-2 dir-right)
        (move-dir pos-5-2 pos-5-1 dir-up)
        (move-dir pos-5-2 pos-5-3 dir-down)
        (move-dir pos-4-4 pos-3-4 dir-left)
        (move-dir pos-4-4 pos-5-4 dir-right)
        (move-dir pos-4-4 pos-4-3 dir-up)
        (move-dir pos-4-4 pos-4-5 dir-down)
        (move-dir pos-5-5 pos-4-5 dir-left)
        (move-dir pos-5-5 pos-6-5 dir-right)
        (move-dir pos-5-5 pos-5-4 dir-up)
        (move-dir pos-5-5 pos-5-6 dir-down)
        (move-dir pos-0-0 pos-1-0 dir-right)
        (move-dir pos-0-0 pos-0-1 dir-down)
        (move-dir pos-0-3 pos-1-3 dir-right)
        (move-dir pos-0-3 pos-0-2 dir-up)
        (move-dir pos-0-3 pos-0-4 dir-down)
        (move-dir pos-2-0 pos-1-0 dir-left)
        (move-dir pos-2-0 pos-3-0 dir-right)
        (move-dir pos-2-0 pos-2-1 dir-down)
        (move-dir pos-0-6 pos-1-6 dir-right)
        (move-dir pos-0-6 pos-0-5 dir-up)
        (move-dir pos-2-6 pos-1-6 dir-left)
        (move-dir pos-2-6 pos-3-6 dir-right)
        (move-dir pos-2-6 pos-2-5 dir-up)
        (move-dir pos-6-0 pos-5-0 dir-left)
        (move-dir pos-6-0 pos-6-1 dir-down)
        (move-dir pos-6-6 pos-5-6 dir-left)
        (move-dir pos-6-6 pos-6-5 dir-up)
        (move-dir pos-6-3 pos-5-3 dir-left)
        (move-dir pos-6-3 pos-6-2 dir-up)
        (move-dir pos-6-3 pos-6-4 dir-down)
  )

  (:goal
    (and
        (exists (?pl - plate)
            (served ?pl mashed-carrot-banana-food)
        )
        (exists (?pl - plate)
            (served ?pl tomato-salad-food)
        )

    )
  )
)