(define (problem p4212043519-overcooked)
  (:domain overcooked)

  (:objects
        pos-0-0 pos-0-1 pos-0-2 pos-0-3 pos-0-4 pos-0-5 pos-0-6 pos-0-7 pos-0-8 pos-1-0 pos-1-1 pos-1-2 pos-1-3 pos-1-4 pos-1-5 pos-1-6 pos-1-7 pos-1-8 pos-2-0 pos-2-1 pos-2-2 pos-2-3 pos-2-4 pos-2-5 pos-2-6 pos-2-7 pos-2-8 pos-3-0 pos-3-1 pos-3-2 pos-3-3 pos-3-4 pos-3-5 pos-3-6 pos-3-7 pos-3-8 pos-4-0 pos-4-1 pos-4-2 pos-4-3 pos-4-4 pos-4-5 pos-4-6 pos-4-7 pos-4-8 pos-5-0 pos-5-1 pos-5-2 pos-5-3 pos-5-4 pos-5-5 pos-5-6 pos-5-7 pos-5-8 pos-6-0 pos-6-1 pos-6-2 pos-6-3 pos-6-4 pos-6-5 pos-6-6 pos-6-7 pos-6-8 pos-7-0 pos-7-1 pos-7-2 pos-7-3 pos-7-4 pos-7-5 pos-7-6 pos-7-7 pos-7-8 pos-8-0 pos-8-1 pos-8-2 pos-8-3 pos-8-4 pos-8-5 pos-8-6 pos-8-7 pos-8-8 - location
        cutboard-01 - cutboard
        blender-01 - blender
        deliversquare-01 deliversquare-02 - deliversquare
        counter-01 counter-02 counter-03 counter-04 counter-05 counter-06 counter-07 counter-08 counter-09 counter-10 counter-11 counter-12 counter-13 counter-14 counter-15 counter-16 counter-17 counter-18 counter-19 counter-20 counter-21 counter-22 counter-23 counter-24 counter-25 counter-26 counter-27 counter-28 counter-29 counter-30 counter-31 counter-32 counter-33 counter-34 counter-35 counter-36 counter-37 counter-38 counter-39 counter-40 counter-41 counter-42 counter-43 counter-44 counter-45 counter-46 counter-47 counter-48 counter-49 counter-50 counter-51 counter-52 - counter
        plate-01 plate-02 - plate
        carrot-01 carrot-02 - carrot
        banana-01 banana-02 - banana
  )

  (:init
        ;; How many quantities when chopping
        (quantity-after-chop onion-type num1)
        (quantity-after-chop tomato-type num1)
        (quantity-after-chop lettuce-type num1)
        (quantity-after-chop cucumber-type num1)
        (quantity-after-chop apple-type num1)
        (quantity-after-chop watermelon-type num1)
        (quantity-after-chop bread-type num2)
        (quantity-after-chop carrot-type num1)
        (quantity-after-chop banana-type num1)
        ;; numeric successor relation for numbers
        (succ num0 num1)
        (succ num1 num2)
        ;; type information for items
        (has-type carrot-01 carrot-type)
        (has-type carrot-02 carrot-type)
        (has-type banana-01 banana-type)
        (has-type banana-02 banana-type)
        ;; init cutboard and blender states -- empty at the start
        (chopped-food-count cutboard-01 num0)
        (smashed-food-count blender-01 num0)
        ;; location facts
        (clear pos-3-4)
        (clear pos-3-7)
        (clear pos-5-4)
        (clear pos-5-1)
        (clear pos-5-7)
        (clear pos-7-4)
        (clear pos-6-2)
        (clear pos-7-1)
        (clear pos-7-7)
        (clear pos-6-5)
        (clear pos-4-5)
        (clear pos-5-6)
        (clear pos-3-6)
        (clear pos-5-3)
        (clear pos-2-7)
        (clear pos-6-1)
        (clear pos-7-3)
        (clear pos-6-7)
        (clear pos-7-6)
        (clear pos-4-7)
        (clear pos-3-5)
        (clear pos-5-2)
        (clear pos-4-4)
        (clear pos-5-5)
        (clear pos-7-2)
        (clear pos-6-6)
        (clear pos-7-5)
        (clear pos-6-3)
        (on counter-01 pos-4-0)
        (on counter-02 pos-4-3)
        (on counter-03 pos-3-1)
        (on counter-04 pos-4-6)
        (on counter-05 pos-8-0)
        (on counter-06 pos-0-2)
        (on counter-07 pos-8-3)
        (on counter-08 pos-0-5)
        (on counter-09 pos-2-2)
        (on counter-10 pos-1-0)
        (on counter-11 pos-1-6)
        (on counter-12 pos-8-6)
        (on counter-13 pos-2-5)
        (on counter-14 pos-1-3)
        (on counter-15 pos-0-8)
        (on counter-16 pos-2-8)
        (on counter-17 pos-6-8)
        (on counter-18 pos-4-2)
        (on counter-19 pos-3-0)
        (on counter-20 pos-3-3)
        (on counter-21 pos-5-0)
        (on counter-22 pos-4-8)
        (on counter-23 pos-8-2)
        (on counter-24 pos-8-5)
        (on counter-25 pos-0-1)
        (on counter-26 pos-0-7)
        (on counter-27 pos-2-4)
        (on counter-28 pos-1-2)
        (on counter-29 pos-0-4)
        (on counter-30 pos-2-1)
        (on counter-31 pos-8-8)
        (on counter-32 pos-1-5)
        (on counter-33 pos-7-0)
        (on counter-34 pos-1-8)
        (on counter-35 pos-3-2)
        (on counter-36 pos-4-1)
        (on counter-37 pos-3-8)
        (on counter-38 pos-8-4)
        (on counter-39 pos-0-0)
        (on counter-40 pos-8-1)
        (on counter-41 pos-8-7)
        (on counter-42 pos-1-1)
        (on counter-43 pos-0-3)
        (on counter-44 pos-2-0)
        (on counter-45 pos-5-8)
        (on counter-46 pos-1-4)
        (on counter-47 pos-0-6)
        (on counter-48 pos-2-3)
        (on counter-49 pos-1-7)
        (on counter-50 pos-2-6)
        (on counter-51 pos-6-0)
        (on counter-52 pos-7-8)
        (on cutboard-01 pos-4-1)
        (on blender-01 pos-4-8)
        (on deliversquare-01 pos-8-7)
        (on deliversquare-02 pos-5-8)
        (at plate-01 pos-3-8)
        (at plate-02 pos-1-7)
        (at carrot-01 pos-7-0)
        (at carrot-02 pos-8-6)
        (at banana-01 pos-2-5)
        (at banana-02 pos-4-6)
        (at agent-01 pos-6-4)
        (handempty agent-01)
        ;; directional adjacency facts
        (move-dir pos-3-4 pos-2-4 dir-left)
        (move-dir pos-3-4 pos-4-4 dir-right)
        (move-dir pos-3-4 pos-3-3 dir-up)
        (move-dir pos-3-4 pos-3-5 dir-down)
        (move-dir pos-3-7 pos-2-7 dir-left)
        (move-dir pos-3-7 pos-4-7 dir-right)
        (move-dir pos-3-7 pos-3-6 dir-up)
        (move-dir pos-3-7 pos-3-8 dir-down)
        (move-dir pos-5-4 pos-4-4 dir-left)
        (move-dir pos-5-4 pos-6-4 dir-right)
        (move-dir pos-5-4 pos-5-3 dir-up)
        (move-dir pos-5-4 pos-5-5 dir-down)
        (move-dir pos-5-1 pos-4-1 dir-left)
        (move-dir pos-5-1 pos-6-1 dir-right)
        (move-dir pos-5-1 pos-5-0 dir-up)
        (move-dir pos-5-1 pos-5-2 dir-down)
        (move-dir pos-5-7 pos-4-7 dir-left)
        (move-dir pos-5-7 pos-6-7 dir-right)
        (move-dir pos-5-7 pos-5-6 dir-up)
        (move-dir pos-5-7 pos-5-8 dir-down)
        (move-dir pos-7-4 pos-6-4 dir-left)
        (move-dir pos-7-4 pos-8-4 dir-right)
        (move-dir pos-7-4 pos-7-3 dir-up)
        (move-dir pos-7-4 pos-7-5 dir-down)
        (move-dir pos-6-2 pos-5-2 dir-left)
        (move-dir pos-6-2 pos-7-2 dir-right)
        (move-dir pos-6-2 pos-6-1 dir-up)
        (move-dir pos-6-2 pos-6-3 dir-down)
        (move-dir pos-7-1 pos-6-1 dir-left)
        (move-dir pos-7-1 pos-8-1 dir-right)
        (move-dir pos-7-1 pos-7-0 dir-up)
        (move-dir pos-7-1 pos-7-2 dir-down)
        (move-dir pos-7-7 pos-6-7 dir-left)
        (move-dir pos-7-7 pos-8-7 dir-right)
        (move-dir pos-7-7 pos-7-6 dir-up)
        (move-dir pos-7-7 pos-7-8 dir-down)
        (move-dir pos-6-5 pos-5-5 dir-left)
        (move-dir pos-6-5 pos-7-5 dir-right)
        (move-dir pos-6-5 pos-6-4 dir-up)
        (move-dir pos-6-5 pos-6-6 dir-down)
        (move-dir pos-4-5 pos-3-5 dir-left)
        (move-dir pos-4-5 pos-5-5 dir-right)
        (move-dir pos-4-5 pos-4-4 dir-up)
        (move-dir pos-4-5 pos-4-6 dir-down)
        (move-dir pos-5-6 pos-4-6 dir-left)
        (move-dir pos-5-6 pos-6-6 dir-right)
        (move-dir pos-5-6 pos-5-5 dir-up)
        (move-dir pos-5-6 pos-5-7 dir-down)
        (move-dir pos-3-6 pos-2-6 dir-left)
        (move-dir pos-3-6 pos-4-6 dir-right)
        (move-dir pos-3-6 pos-3-5 dir-up)
        (move-dir pos-3-6 pos-3-7 dir-down)
        (move-dir pos-5-3 pos-4-3 dir-left)
        (move-dir pos-5-3 pos-6-3 dir-right)
        (move-dir pos-5-3 pos-5-2 dir-up)
        (move-dir pos-5-3 pos-5-4 dir-down)
        (move-dir pos-2-7 pos-1-7 dir-left)
        (move-dir pos-2-7 pos-3-7 dir-right)
        (move-dir pos-2-7 pos-2-6 dir-up)
        (move-dir pos-2-7 pos-2-8 dir-down)
        (move-dir pos-6-1 pos-5-1 dir-left)
        (move-dir pos-6-1 pos-7-1 dir-right)
        (move-dir pos-6-1 pos-6-0 dir-up)
        (move-dir pos-6-1 pos-6-2 dir-down)
        (move-dir pos-6-4 pos-5-4 dir-left)
        (move-dir pos-6-4 pos-7-4 dir-right)
        (move-dir pos-6-4 pos-6-3 dir-up)
        (move-dir pos-6-4 pos-6-5 dir-down)
        (move-dir pos-7-3 pos-6-3 dir-left)
        (move-dir pos-7-3 pos-8-3 dir-right)
        (move-dir pos-7-3 pos-7-2 dir-up)
        (move-dir pos-7-3 pos-7-4 dir-down)
        (move-dir pos-6-7 pos-5-7 dir-left)
        (move-dir pos-6-7 pos-7-7 dir-right)
        (move-dir pos-6-7 pos-6-6 dir-up)
        (move-dir pos-6-7 pos-6-8 dir-down)
        (move-dir pos-7-6 pos-6-6 dir-left)
        (move-dir pos-7-6 pos-8-6 dir-right)
        (move-dir pos-7-6 pos-7-5 dir-up)
        (move-dir pos-7-6 pos-7-7 dir-down)
        (move-dir pos-4-7 pos-3-7 dir-left)
        (move-dir pos-4-7 pos-5-7 dir-right)
        (move-dir pos-4-7 pos-4-6 dir-up)
        (move-dir pos-4-7 pos-4-8 dir-down)
        (move-dir pos-3-5 pos-2-5 dir-left)
        (move-dir pos-3-5 pos-4-5 dir-right)
        (move-dir pos-3-5 pos-3-4 dir-up)
        (move-dir pos-3-5 pos-3-6 dir-down)
        (move-dir pos-5-2 pos-4-2 dir-left)
        (move-dir pos-5-2 pos-6-2 dir-right)
        (move-dir pos-5-2 pos-5-1 dir-up)
        (move-dir pos-5-2 pos-5-3 dir-down)
        (move-dir pos-4-4 pos-3-4 dir-left)
        (move-dir pos-4-4 pos-5-4 dir-right)
        (move-dir pos-4-4 pos-4-3 dir-up)
        (move-dir pos-4-4 pos-4-5 dir-down)
        (move-dir pos-5-5 pos-4-5 dir-left)
        (move-dir pos-5-5 pos-6-5 dir-right)
        (move-dir pos-5-5 pos-5-4 dir-up)
        (move-dir pos-5-5 pos-5-6 dir-down)
        (move-dir pos-7-2 pos-6-2 dir-left)
        (move-dir pos-7-2 pos-8-2 dir-right)
        (move-dir pos-7-2 pos-7-1 dir-up)
        (move-dir pos-7-2 pos-7-3 dir-down)
        (move-dir pos-6-6 pos-5-6 dir-left)
        (move-dir pos-6-6 pos-7-6 dir-right)
        (move-dir pos-6-6 pos-6-5 dir-up)
        (move-dir pos-6-6 pos-6-7 dir-down)
        (move-dir pos-7-5 pos-6-5 dir-left)
        (move-dir pos-7-5 pos-8-5 dir-right)
        (move-dir pos-7-5 pos-7-4 dir-up)
        (move-dir pos-7-5 pos-7-6 dir-down)
        (move-dir pos-6-3 pos-5-3 dir-left)
        (move-dir pos-6-3 pos-7-3 dir-right)
        (move-dir pos-6-3 pos-6-2 dir-up)
        (move-dir pos-6-3 pos-6-4 dir-down)
        (move-dir pos-4-0 pos-3-0 dir-left)
        (move-dir pos-4-0 pos-5-0 dir-right)
        (move-dir pos-4-0 pos-4-1 dir-down)
        (move-dir pos-4-3 pos-3-3 dir-left)
        (move-dir pos-4-3 pos-5-3 dir-right)
        (move-dir pos-4-3 pos-4-2 dir-up)
        (move-dir pos-4-3 pos-4-4 dir-down)
        (move-dir pos-3-1 pos-2-1 dir-left)
        (move-dir pos-3-1 pos-4-1 dir-right)
        (move-dir pos-3-1 pos-3-0 dir-up)
        (move-dir pos-3-1 pos-3-2 dir-down)
        (move-dir pos-4-6 pos-3-6 dir-left)
        (move-dir pos-4-6 pos-5-6 dir-right)
        (move-dir pos-4-6 pos-4-5 dir-up)
        (move-dir pos-4-6 pos-4-7 dir-down)
        (move-dir pos-8-0 pos-7-0 dir-left)
        (move-dir pos-8-0 pos-8-1 dir-down)
        (move-dir pos-0-2 pos-1-2 dir-right)
        (move-dir pos-0-2 pos-0-1 dir-up)
        (move-dir pos-0-2 pos-0-3 dir-down)
        (move-dir pos-8-3 pos-7-3 dir-left)
        (move-dir pos-8-3 pos-8-2 dir-up)
        (move-dir pos-8-3 pos-8-4 dir-down)
        (move-dir pos-0-5 pos-1-5 dir-right)
        (move-dir pos-0-5 pos-0-4 dir-up)
        (move-dir pos-0-5 pos-0-6 dir-down)
        (move-dir pos-2-2 pos-1-2 dir-left)
        (move-dir pos-2-2 pos-3-2 dir-right)
        (move-dir pos-2-2 pos-2-1 dir-up)
        (move-dir pos-2-2 pos-2-3 dir-down)
        (move-dir pos-1-0 pos-0-0 dir-left)
        (move-dir pos-1-0 pos-2-0 dir-right)
        (move-dir pos-1-0 pos-1-1 dir-down)
        (move-dir pos-1-6 pos-0-6 dir-left)
        (move-dir pos-1-6 pos-2-6 dir-right)
        (move-dir pos-1-6 pos-1-5 dir-up)
        (move-dir pos-1-6 pos-1-7 dir-down)
        (move-dir pos-8-6 pos-7-6 dir-left)
        (move-dir pos-8-6 pos-8-5 dir-up)
        (move-dir pos-8-6 pos-8-7 dir-down)
        (move-dir pos-2-5 pos-1-5 dir-left)
        (move-dir pos-2-5 pos-3-5 dir-right)
        (move-dir pos-2-5 pos-2-4 dir-up)
        (move-dir pos-2-5 pos-2-6 dir-down)
        (move-dir pos-1-3 pos-0-3 dir-left)
        (move-dir pos-1-3 pos-2-3 dir-right)
        (move-dir pos-1-3 pos-1-2 dir-up)
        (move-dir pos-1-3 pos-1-4 dir-down)
        (move-dir pos-0-8 pos-1-8 dir-right)
        (move-dir pos-0-8 pos-0-7 dir-up)
        (move-dir pos-2-8 pos-1-8 dir-left)
        (move-dir pos-2-8 pos-3-8 dir-right)
        (move-dir pos-2-8 pos-2-7 dir-up)
        (move-dir pos-6-8 pos-5-8 dir-left)
        (move-dir pos-6-8 pos-7-8 dir-right)
        (move-dir pos-6-8 pos-6-7 dir-up)
        (move-dir pos-4-2 pos-3-2 dir-left)
        (move-dir pos-4-2 pos-5-2 dir-right)
        (move-dir pos-4-2 pos-4-1 dir-up)
        (move-dir pos-4-2 pos-4-3 dir-down)
        (move-dir pos-3-0 pos-2-0 dir-left)
        (move-dir pos-3-0 pos-4-0 dir-right)
        (move-dir pos-3-0 pos-3-1 dir-down)
        (move-dir pos-3-3 pos-2-3 dir-left)
        (move-dir pos-3-3 pos-4-3 dir-right)
        (move-dir pos-3-3 pos-3-2 dir-up)
        (move-dir pos-3-3 pos-3-4 dir-down)
        (move-dir pos-5-0 pos-4-0 dir-left)
        (move-dir pos-5-0 pos-6-0 dir-right)
        (move-dir pos-5-0 pos-5-1 dir-down)
        (move-dir pos-4-8 pos-3-8 dir-left)
        (move-dir pos-4-8 pos-5-8 dir-right)
        (move-dir pos-4-8 pos-4-7 dir-up)
        (move-dir pos-8-2 pos-7-2 dir-left)
        (move-dir pos-8-2 pos-8-1 dir-up)
        (move-dir pos-8-2 pos-8-3 dir-down)
        (move-dir pos-8-5 pos-7-5 dir-left)
        (move-dir pos-8-5 pos-8-4 dir-up)
        (move-dir pos-8-5 pos-8-6 dir-down)
        (move-dir pos-0-1 pos-1-1 dir-right)
        (move-dir pos-0-1 pos-0-0 dir-up)
        (move-dir pos-0-1 pos-0-2 dir-down)
        (move-dir pos-0-7 pos-1-7 dir-right)
        (move-dir pos-0-7 pos-0-6 dir-up)
        (move-dir pos-0-7 pos-0-8 dir-down)
        (move-dir pos-2-4 pos-1-4 dir-left)
        (move-dir pos-2-4 pos-3-4 dir-right)
        (move-dir pos-2-4 pos-2-3 dir-up)
        (move-dir pos-2-4 pos-2-5 dir-down)
        (move-dir pos-1-2 pos-0-2 dir-left)
        (move-dir pos-1-2 pos-2-2 dir-right)
        (move-dir pos-1-2 pos-1-1 dir-up)
        (move-dir pos-1-2 pos-1-3 dir-down)
        (move-dir pos-0-4 pos-1-4 dir-right)
        (move-dir pos-0-4 pos-0-3 dir-up)
        (move-dir pos-0-4 pos-0-5 dir-down)
        (move-dir pos-2-1 pos-1-1 dir-left)
        (move-dir pos-2-1 pos-3-1 dir-right)
        (move-dir pos-2-1 pos-2-0 dir-up)
        (move-dir pos-2-1 pos-2-2 dir-down)
        (move-dir pos-8-8 pos-7-8 dir-left)
        (move-dir pos-8-8 pos-8-7 dir-up)
        (move-dir pos-1-5 pos-0-5 dir-left)
        (move-dir pos-1-5 pos-2-5 dir-right)
        (move-dir pos-1-5 pos-1-4 dir-up)
        (move-dir pos-1-5 pos-1-6 dir-down)
        (move-dir pos-7-0 pos-6-0 dir-left)
        (move-dir pos-7-0 pos-8-0 dir-right)
        (move-dir pos-7-0 pos-7-1 dir-down)
        (move-dir pos-1-8 pos-0-8 dir-left)
        (move-dir pos-1-8 pos-2-8 dir-right)
        (move-dir pos-1-8 pos-1-7 dir-up)
        (move-dir pos-3-2 pos-2-2 dir-left)
        (move-dir pos-3-2 pos-4-2 dir-right)
        (move-dir pos-3-2 pos-3-1 dir-up)
        (move-dir pos-3-2 pos-3-3 dir-down)
        (move-dir pos-4-1 pos-3-1 dir-left)
        (move-dir pos-4-1 pos-5-1 dir-right)
        (move-dir pos-4-1 pos-4-0 dir-up)
        (move-dir pos-4-1 pos-4-2 dir-down)
        (move-dir pos-3-8 pos-2-8 dir-left)
        (move-dir pos-3-8 pos-4-8 dir-right)
        (move-dir pos-3-8 pos-3-7 dir-up)
        (move-dir pos-8-4 pos-7-4 dir-left)
        (move-dir pos-8-4 pos-8-3 dir-up)
        (move-dir pos-8-4 pos-8-5 dir-down)
        (move-dir pos-0-0 pos-1-0 dir-right)
        (move-dir pos-0-0 pos-0-1 dir-down)
        (move-dir pos-8-1 pos-7-1 dir-left)
        (move-dir pos-8-1 pos-8-0 dir-up)
        (move-dir pos-8-1 pos-8-2 dir-down)
        (move-dir pos-8-7 pos-7-7 dir-left)
        (move-dir pos-8-7 pos-8-6 dir-up)
        (move-dir pos-8-7 pos-8-8 dir-down)
        (move-dir pos-1-1 pos-0-1 dir-left)
        (move-dir pos-1-1 pos-2-1 dir-right)
        (move-dir pos-1-1 pos-1-0 dir-up)
        (move-dir pos-1-1 pos-1-2 dir-down)
        (move-dir pos-0-3 pos-1-3 dir-right)
        (move-dir pos-0-3 pos-0-2 dir-up)
        (move-dir pos-0-3 pos-0-4 dir-down)
        (move-dir pos-2-0 pos-1-0 dir-left)
        (move-dir pos-2-0 pos-3-0 dir-right)
        (move-dir pos-2-0 pos-2-1 dir-down)
        (move-dir pos-5-8 pos-4-8 dir-left)
        (move-dir pos-5-8 pos-6-8 dir-right)
        (move-dir pos-5-8 pos-5-7 dir-up)
        (move-dir pos-1-4 pos-0-4 dir-left)
        (move-dir pos-1-4 pos-2-4 dir-right)
        (move-dir pos-1-4 pos-1-3 dir-up)
        (move-dir pos-1-4 pos-1-5 dir-down)
        (move-dir pos-0-6 pos-1-6 dir-right)
        (move-dir pos-0-6 pos-0-5 dir-up)
        (move-dir pos-0-6 pos-0-7 dir-down)
        (move-dir pos-2-3 pos-1-3 dir-left)
        (move-dir pos-2-3 pos-3-3 dir-right)
        (move-dir pos-2-3 pos-2-2 dir-up)
        (move-dir pos-2-3 pos-2-4 dir-down)
        (move-dir pos-1-7 pos-0-7 dir-left)
        (move-dir pos-1-7 pos-2-7 dir-right)
        (move-dir pos-1-7 pos-1-6 dir-up)
        (move-dir pos-1-7 pos-1-8 dir-down)
        (move-dir pos-2-6 pos-1-6 dir-left)
        (move-dir pos-2-6 pos-3-6 dir-right)
        (move-dir pos-2-6 pos-2-5 dir-up)
        (move-dir pos-2-6 pos-2-7 dir-down)
        (move-dir pos-6-0 pos-5-0 dir-left)
        (move-dir pos-6-0 pos-7-0 dir-right)
        (move-dir pos-6-0 pos-6-1 dir-down)
        (move-dir pos-7-8 pos-6-8 dir-left)
        (move-dir pos-7-8 pos-8-8 dir-right)
        (move-dir pos-7-8 pos-7-7 dir-up)
  )

  (:goal
    (and
        (exists (?pl - plate)
            (served ?pl carrot-banana-food)
        )

    )
  )
)